apiVersion: v1
kind: LimitRange
metadata:
  name: default-lr
spec:
  limits:
  - default:
      cpu: 1000m
      ephemeral-storage: 1Gi
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      ephemeral-storage: 512Mi
      memory: 128Mi
    type: Container
