apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ardikabs-com
spec:
  acme:
    email: info@ardikabs.com
    privateKeySecretRef:
      name: letsencrypt-ardikabs-com
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
