apiVersion: v1
kind: LimitRange
metadata:
  name: default-lr
spec:
  limits:
  - default:
      cpu: 3000m
      ephemeral-storage: 1Gi
      memory: 6Gi
    defaultRequest:
      cpu: 1000m
      ephemeral-storage: 512Mi
      memory: 1000Mi
    type: Container
