apiVersion: v1
kind: LimitRange
metadata:
  name: default-lr
spec:
  limits:
  - default:
      cpu: 2000m
      ephemeral-storage: 1Gi
      memory: 4Gi
    defaultRequest:
      cpu: 500m
      ephemeral-storage: 512Mi
      memory: 512Mi
    type: Container
